crypto/ed25519: support signature verification
cue-lang/cue pull request #1184
Opened 2021-08-03 21:14 UTC by oncilla

Add support for ed25519 signature verification of message based on
a public key.

fixes #331

Signed-off-by: Dominik Roos <domi.roos@gmail.com>

2021-08-03 21:18 UTC, oncilla commented
I was not sure how to do the testdata file.
If you have a better pattern for generating the golden file, let me know.

2021-08-03 21:56 UTC, verdverm commented
re: golden file, there is a way to run the testsuite in update mode (https://github.com/cue-lang/cue/blob/a9b13e823e76986cf8722edf04174f8ee10c525c/internal/cuetxtar/txtar.go#L323) not sure how to invoke that myself though...

Seems like a good topic to add to https://github.com/cue-lang/cue/wiki/Contribution-tips-and-tricks, and generally guidance on writing such tests

2021-08-03 22:08 UTC, oncilla commented
Oh, I see. It is done via env var here: https://github.com/cue-lang/cue/blob/a9b13e823e76986cf8722edf04174f8ee10c525c/internal/cuetest/cuetest.go#L56

Hm, but that update does not really fit, because we need to generate valid signatures. But we could get rid of the manual output generation.

Thanks for the hint 👍 
I will play around with.it tomorrow.

2021-08-04 15:48 UTC, oncilla commented
I updated the test to use `cuetest.UpdateGoldenFiles`

To update the golden files, you can simply run the following:

```sh
CUE_UPDATE=true go test ./pkg/crypto/ed25519/
```

2021-08-10 11:03 UTC, myitcv commented
Thanks @oncilla - @mpvl and I are, independently, taking some vacation at the moment so we will get back to this on our return.

2021-08-10 16:08 UTC, oncilla commented
No worries, enjoy!

2022-02-18 14:50 UTC, mpvl requested changes
Sorry for the enormous delay. 

This generally looks good. We have one small tweak that we need to do in Gerrit, also because we can't run CI on GH right now.

2022-02-18 14:50 UTC, mpvl commented on pkg/crypto/ed25519/ed25519.go
> +func Verify(publicKey, message, signature []byte) (bool, error) {
Both the proposal and the convention within CUE is to call this `Valid`, for better or for worse.

2022-02-18 14:55 UTC, myitcv approved these changes
LGTM with the caveat @mpvl mentioned in https://github.com/cue-lang/cue/pull/1184#discussion_r810067255

2022-02-18 15:14 UTC, closed without merging

2022-02-18 15:52 UTC, oncilla commented
:tada: