Add CIDR range verification function in net package
cue-lang/cue pull request #1301
Opened 2021-10-15 12:43 UTC by jared-gs

I've added a CIDR verification function, which helps in use-cases where CIDR ranges (and not individual IP addresses) need to be checked.

2021-10-15 13:07 UTC, seh commented on pkg/net/ip.go
> +// IPCIDR reports whether s is a valid IPv4 or IPv6 address with CIDR subnet notation
```suggestion
// IPCIDR reports whether ip is a valid IPv4 or IPv6 address with CIDR subnet notation.
```

2021-10-15 13:20 UTC, jared-gs commented on pkg/net/ip.go
> +// IPCIDR reports whether s is a valid IPv4 or IPv6 address with CIDR subnet notation
Updated, thanks. I will note other functions in this package will need similar edits.

2022-02-18 13:50 UTC, mpvl requested changes

2022-02-18 13:50 UTC, mpvl commented on pkg/net/ip.go
> +	return netGetIPCIDR(ip) != nil
CUE can pass error messages back to the user if you use the `IPCIDR(ip cue.Value) (bool, error)` signature. I know it looks strange, but I would do that here for the sake of better error messages.

2022-02-18 15:38 UTC, closed without merging