specify default constratin is not implemented
cue-lang/cue pull request #1471
Opened 2022-01-15 05:58 UTC by cuichenli

Related to https://github.com/cue-lang/cue/issues/1109

2022-01-29 06:54 UTC, myitcv commented
Thanks very much for raising this. 

Please can update the commit message per the [contribution guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#good-commit-messages) so that it reads something like:


```
doc/spec: specify default constraint is not implemented

For #1109
```

The first line comment then tells someone briefly what the change corresponds to, the use of `For` in the body relates it to the linked issue but does not close it (this is a convention we have adopted from the Go project).

2022-02-10 13:37 UTC, myitcv requested changes
@cuichenli gentle nudge on the commit message format.

Also some proposed changes on the wording to keep things simple and consistent.

Otherwise, we're very happy to add these notes to the spec, not least because it's the reference many people look towards.

2022-02-10 13:37 UTC, myitcv commented on doc/ref/spec.md
> +_Note_: This behavior is not implemented yet.
```
_Note_: default constraints are not yet implemented.
```

2022-02-10 13:37 UTC, myitcv commented on doc/ref/spec.md
> +with another struct using pattern or default constraints (_Note_: The feature of
```
... default constraints. (_Note_: default constraints are not yet implemented).
```

2022-02-10 13:37 UTC, myitcv commented on doc/ref/spec.md
> +    ...string         // all other fields must be a string. Note: to be implemented.
```
// all other fields must be a string. Note: default constraints are not yet implemented.
```

2022-02-11 02:44 UTC, cuichenli commented
@myitcv sorry i was away for a while and just got back. 
just updated the commit message and wording. please kindly check again. thanks

2022-02-17 11:35 UTC, myitcv approved these changes
LGTM. Thanks very much for your patience fixing up commits messages etc.

2022-02-17 11:39 UTC, myitcv commented
Submitted as 1c52d6a7d693133f04810da355f8036848c2c78a

2022-02-17 11:39 UTC, closed without merging