cmd/cue: fix help cmd incorrect behavior
cue-lang/cue pull request #2759
Opened 2024-01-06 09:15 UTC by nnnkkk7

This fixes the issue of incorrect behavior when requesting help for an unknown command in the CUE CLI.

1. Modified the  function to handle unknown commands correctly.
2. When an unknown  and  commands are entered, an error message is displayed and the program exits with a non-zero status code.
3. This ensures that the CLI behaves as expected and provides useful feedback to the user when an unknown command is entered.

 Fixes #2560

2024-01-06 10:32 UTC, mvdan commented
This would need a test; see the other `cue help` test scripts.

Also, I suspect this will break existing tests. Did you run them?

2024-01-06 10:33 UTC, mvdan requested changes
See the above

2024-01-08 05:42 UTC, nnnkkk7 commented
thanks! i fixed it!

2024-01-08 11:13 UTC, mvdan commented
> This would need a test; see the other `cue help` test scripts.

See the above - if you are fixing a bug, a test should be added. See https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md

2024-01-14 07:56 UTC, nnnkkk7 commented
I missed it. Sorry, I added the test.
[add test for os.Exit(1)](https://github.com/cue-lang/cue/pull/2759/commits/ecc3ffa3541d07afded0431098160cfa79f1d40b)

2024-03-20 18:45 UTC, mvdan commented
Thanks! No need to write a Go test and mock os.Exit for this; we already have integration tests for cmd/go at cmd/cue/cmd/testdata/script/help.txtar and sibling files like help_cmd.txtar, for example.

Also, is there a particular reason that you swapped Printf and CheckErr for PrintErrf and os.Exit? As far as I can tell, the fix here is the addition of `|| len(rests) != 0`, so the other bits of the PR shouldn't be necessary.

2024-05-03 13:06 UTC, mvdan commented
Did the above, as well as added more test cases, in this Gerrit patch: https://review.gerrithub.io/c/cue-lang/cue/+/1194247

Hope that's okay with you, and please let me know if you spot any issues there.

2024-05-03 13:14 UTC, closed without merging